POST http://localhost:4000/api/wilders
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "description": "Lorem Ipsum",
  "isTeacher": true,
  "school": "WCS-LYON",
  "skills": [
          {
            "skillName": "C#",
          },
          {
            "skillName": "Ruby",
          },
          {
            "skillName": "PHP",
          },
          {
            "skillName": "Java",
          },
          {
            "skillName": "Python",
          },
          {
            "skillName": "C+",
          },
          {
            "skillName": "JS",
          },
        ]
}